language: android
dist: trusty
android:
    components:
      - tools


      - build-tools-29.0.3
      - android-27

      # Support library
      - extra-android-support
      - extra-android-m2repository

script:
  - chmod +x ./gradlew
