language: android
dist: trusty
deploy:
  provider: releases
  api_key: "1f6e35987446cd960cf3441036a04d9ff3bb86d6"
  file: "release.apk"
  skip_cleanup: true

android:
    components:
      - tools


      - build-tools-29.0.3
      - android-27

      # Support library
      - extra-android-support
      - extra-android-m2repository

script:
  - chmod +x ./gradlew
